# Generated by Django 3.2.25 on 2024-04-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20240428_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='url',
            new_name='name',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
