name: Auto deploy to EC2 instance

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS CodeDeploy
      run: |
        aws deploy push --application-name ecommerce \
          --s3-location s3://ecommerce-bucket-dxn/ecommerce.zip

        aws deploy create-deployment --application-name ecommerce \
          --deployment-group-name ecommerce \
          --s3-location bucket=ecommerce-bucket-dxn,key=ecommerce.zip,bundleType=zip
