name: Django CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS CodeDeploy
      run: |
        aws deploy push --application-name my-django-blog \
          --s3-location s3://escapa-la-matrix-s3-bucket/my-django-blog.zip

        aws deploy create-deployment --application-name my-django-blog \
          --deployment-group-name my-django-blog-group \
          --s3-location bucket=escapa-la-matrix-s3-bucket,key=my-django-blog.zip,bundleType=zip
